/* AUTO-GENERATED by scripts/generate-build-meta.mjs — do not edit by hand */
import type { BuildInfo } from './types.js';

export const GENERATED_BUILD_META = {
  "name": "Saki Operations",
  "version": "1.0.0",
  "build": "837e6f5",
  "builtAt": "2026-07-17T08:46:59.893Z",
  "environment": "development",
  "syncEngine": "1",
  "company": "Saki Tours & Weddings (Pvt) Ltd",
  "website": "https://sakitours.com",
  "copyrightYear": 2026,
  "platform": "Web PWA",
  "supportContact": "operations@sakitours.com",
  "license": "Proprietary"
} as const satisfies BuildInfo;
